sudo: false
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
notifications:
  email: false
script:
- npm run build
- npm test
- npm run lint
addons:
  sauce_connect:
    username: r4k4+IKquk1bCNYSow7a0O3BPB9UZlCDyl1gTNdaLObXqQcrMv4y4u2Sbs69mze2n38rRCli6DSd/zMAPg2J4W7RuI0prhKVzS8oCVPZLMO3fCS7CjhzXo4iMxgaPnZ3J7izx1ANsjI42IKGLRF0jyj/nePhAIayracjyCZ1cRf93Wosneg9R4Wh+YP8AEyk75YFIXgwL3lOfzydffd0AzUml9RQgWFyXBixABKJv6vRod1/+KWgq9mNc0ZpoRoV1DIwqyn73H0S08QJnoHKndosbaPeKM6btPU2DKMk5Mx5Sy2KNXJ2uxboKCdcoPhLOm4u7aoDgbEEF+6mtW4J67g0v13icRwowLUDzMAmkM3ivp/2MB16x/oYN/niCvcBmKbkMqNd4ZH50UM2sfyGnR1Gcw6AIsOAlOw6zesjMbDADBLxxSy4mDwvVIu2plrl+K6v8QmMWcE3HsErhOoyBhnjAl3e+drboePGmhNCG2OVI6i9L19CSg3Q7GVfFjnsZXlccvtv+mktLKoz1Jxue1/OD6XTf/kt0ooJEFHvTkr5oPqWsv4r/jSWCTQSKfgEUtywXaWSCSZRdCybqyiADz8mP/BcxnHJnLbErzEdTIWErWp5mPyLGsOKTSFTHdBBhLxLoHoO0SMZXyeH64Jcoa/VGWykBvtH0vyM16zh0RQ=
  jwt:
    secure: sVz4SvXA09BUi5JWCyU/ve7o9sQmJCs84Upfa5IWepCRH+p4hexgHLQGuAbB5NtAzBW8blZvkApDLBjMeSQFyiwEryKssYgU8jwEnE4rro4FVrpHvJ84vFLqCTWUr/qw6m2wLNSdwvSTojGyIw9w2L2aeQLo/p8po2UDHCBD1fgvkWzEuQTSZP3A3yal11fs3I+xt0GWz2NBpNyMYkyZNfN5q+QraV6ChIb8g+6f3lJjPe8eNIwORXJ75js5epZfIWfas5IEhD2xv4Ej03Vr0JCZNVd0KKEyo9d3LChqCX722DVfmhMq4dP7TEq6xIV2zXoI4gdry04J35T4AJbWmFGkdM50mvAYi5+QlfEWDpPoSly14HW05nPvGxvBG9JFp8NZuKtnlLbyQ1MB2kdDl2BBeDDs9ZxXMrV9ThSe8u0rvYFE55YfCNnEvbpk8TJNJcudnuh51UiNmQCiu+jvuFuyYtX0u2VnYUqTdM0yJ516Oi77TLTusmnP2GLgLJe4syEvrdKduSRQQaFU8Y4gXEzljPY2FbAYNpOQA5VtyorDjDjjIie6DAAZ+ALnwHrrwsFIW7DaIS7VJJjdY/ZXFsbRf0sJlUKHHPMNaQhob2Fq60LgNhNqRY5bdpby2qWMqVVh6SLl1wdOEbP2MHdybiWI5Ooa1Qy/ysJIwZLCjxc=
