sudo: false
language: node_js
node_js:
- '9'
notifications:
  email: true
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- yarn run build
- yarn run ci-test
- yarn run lint
after_script: greenkeeper-lockfile-upload
deploy:
  provider: surge
  project: ./dist/
  domain: asktoni.surge.sh
  skip_cleanup: true