sudo: false
language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
notifications:
  email: false
script:
- npm run build
- npm run ci-test
- npm run lint
- npm run deploy-staging
deploy:
  provider: surge
  project: ./dist/
  domain: asktoni.surge.sh
  skip_cleanup: true